### PR TITLE
Add EXAMPLES.md in summary for HTTP tips

### PR DESCRIPTION
**Pull request by plaurin84**
I added a full path to _'these tips'_ url, for HTTP server staging document, instead of only filename.
Clicking on _'these tips'_ will open the github page instead of downloading a file.

An URL that directly downloads a file is a bit intrusive, and it's better to stick with browser tabs when navigating docs.

### CODE REVIEW

**Comment by jgarnier** [comment]
thanks for the spot @plaurin84, I would recommend not putting full URL, the link is currently not working as EXAMPLE.md is not part of SUMMARY.md which is used by gitbook.

**Comment by plaurin84** [comment]
Right! I understand.
Would it make sense to add it to References then?

**Comment by plaurin84** [comment]
Bear with me, just getting in touch with gitbooks :smile:

**Comment by jgarnier** [comment]
sure, just add it to summary and this will solve the issue. the problem with full URL is that this will only work for develop, not for all branches especially master

**Comment by plaurin84** [comment]
Okay, makes perfect sense. Let me know if that works.

**Comment by jgarnier** [comment]
working fine, thanks for your contribution @plaurin84

**Pull request merged**
